---
- name: Ensure package idependent are installed.
  apt:
    name: "{{ apt_packages_name }}"
    update_cache: true
    state: present
  when: apt_packages_name is defined

- name: Add an Apt signing key for {{ service_name }}
  apt_key:
    url: "{{ apt_gpg_key }}"
    state: present
  when: apt_gpg_key is defined

- name: Ensure Mysql client are installed.
  apt:
    name: "{{ __mysql_package_name }}"
    update_cache: true
    state: present
